version: '3.4'

services:
  nextprojet14:
    image: nextprojet14
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
